import { FC } from 'react'
import { Footer } from '@/src/components/footer'
import { NavBar } from '@/src/components/navbar'
import styles from './styles.module.scss'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const Layout: FC<{
  children: React.ReactNode
}> = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <div className={styles.layout}>
          <NavBar />
          <main className={styles.main}>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  )
}

export default Layout
